import { chromium } from "playwright";
const b = await chromium.launch();
const p = await (await b.newContext({viewport:{width:1440,height:1000}})).newPage();
await p.goto("http://localhost:3305/galeriya",{waitUntil:"networkidle"});
await p.evaluate(()=>window.scrollTo(0,300));
await p.waitForTimeout(1200);
const r = await p.evaluate(()=>{const t=document.querySelector('.break-inside-avoid [role="img"]');const b=t.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:Math.min(b.height,520)};});
await p.screenshot({path:"screenshots/one-tile.png", clip:{x:Math.max(0,r.x),y:Math.max(0,r.y),width:r.w,height:r.h}});
console.log("saved", JSON.stringify(r));
await b.close();
